import type { Metadata } from "next";
import "./globals.css";
import { Header } from "../components/header/Header";
import { Ubuntu } from "next/font/google";

const ubuntu = Ubuntu({ 
  weight: ["300", "400", "500", "700"],
  style:["italic","normal"],
  subsets:["latin"]

});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <Header />
        <main className=" dark:bg-gray-800">{children}</main>
      </body>
    </html>
  );
}
